#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('Symfony Console', '0.1.0');

// ... register commands
$app->add(new CreateUserCommand);

$app->run();
